version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
      - bot
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    networks:
      - app-network

  bot:
    build:
      context: ./bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      NGROK_URL: ${NGROK_URL}
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: profiles
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
